services:
  strapi:
    container_name: strapi
    build:
      context: .
      dockerfile: Dockerfile
    image: react-strapi:latest
    env_file: .env
    environment:
      DATABASE_CLIENT: postgres
      # DATABASE_HOST: strapiDB
      # DATABASE_PORT: 5432
      # DATABASE_NAME: strapi
      # DATABASE_USERNAME: strapi
      # DATABASE_PASSWORD: strapi_password
      DATABASE_SSL: false
      NODE_ENV: ${NODE_ENV:-development}
      # JWT_SECRET: ${JWT_SECRET}
      # ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      # APP_KEYS: ${APP_KEYS}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/app/package.json
      - ./package-lock.json:/opt/app/package-lock.json
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - strapi

  # strapiDB:
  #   container_name: strapiDB
  #   platform: linux/amd64 #for platform error on Apple M1 chips
  #   restart: unless-stopped
  #   image: postgres:15.0-alpine
  #   environment:
  #     POSTGRES_USER: strapi
  #     POSTGRES_PASSWORD: strapi_password
  #     POSTGRES_DB: strapi
  #   volumes:
  #     - strapi-data:/var/lib/postgresql/data/
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - strapi

volumes:
  strapi-data:

networks:
  strapi:
    name: strapi
    driver: bridge 