// Page PUBLIQUE de vérification d'attestation (NTF-004) — cible du QR code du PDF.
//
// Hors groupe (app) : aucune authentification. Confirme l'authenticité d'un document à
// partir de sa `reference` (REC-AAAAMM-XXXX) via la RPC `verify_attestation`. La RPC est
// SECURITY DEFINER + GRANT anon → un client anon (cookies de session vides) suffit ; elle
// ne renvoie AUCUNE PII membre ni montant (divulgation minimale : période, club, émission).
//
// Thème : la page suit le thème du document (script no-flash du layout, clair/sombre via
// tokens) ; aucun thème forcé (contrairement à /acces-suspendu, sombre par design).
//
// Réf : NTF-004/NTF-005, migration 023, CLAUDE.md (tokens only, jamais de NaN/undefined, AA).

import type { Metadata } from 'next'
import { getTranslations } from 'next-intl/server'
import { cookies } from 'next/headers'

import { createServerClient } from '@evolve/data'
import { formatMonth, formatDateLong } from '@evolve/utils'

import { VerificationLayout } from './VerificationLayout'

export const dynamic = 'force-dynamic'

export async function generateMetadata(): Promise<Metadata> {
  const t = await getTranslations('attestationVerify')
  return { title: t('metaTitle') }
}

/** Résultat de la RPC de vérification (divulgation minimale). */
interface VerifyRow {
  period: string
  club_name: string
  issued_at: string
}

/** « 2026-04 » → « avril 2026 » via @evolve/utils (locale FR). Fallback : la chaîne brute. */
function periodLabel(period: string): string {
  const m = /^(\d{4})-(\d{2})$/.exec(period.trim())
  if (!m) return period
  // Jour 1, midi UTC → évite tout décalage de fuseau sur le libellé mois/année.
  return formatMonth(new Date(Date.UTC(Number(m[1]), Number(m[2]) - 1, 1, 12)))
}

export default async function VerifierPage({ params }: { params: Promise<{ ref: string }> }) {
  const { ref } = await params
  const reference = decodeURIComponent(ref)
  const t = await getTranslations('attestationVerify')

  // Client anon (la RPC SECURITY DEFINER ne dépend pas de la session) — RLS contournée
  // uniquement pour exposer les 3 champs non sensibles autorisés par la fonction.
  const cookieStore = await cookies()
  const supabase = createServerClient(cookieStore)
  const { data, error } = await supabase.rpc('verify_attestation', { p_reference: reference })

  const row: VerifyRow | null = !error && Array.isArray(data) && data.length > 0 ? data[0] : null

  return (
    <VerificationLayout reference={reference} title={t('title')}>
      {row ? (
        <div className="flex flex-col gap-5">
          <span
            className="inline-flex w-fit items-center gap-2 rounded-full bg-data-positive-50 px-3 py-1 text-sm font-semibold text-data-positive"
            role="status"
          >
            <svg
              viewBox="0 0 20 20"
              className="h-4 w-4"
              aria-hidden="true"
              focusable="false"
              fill="none"
              stroke="currentColor"
              strokeWidth="2.5"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <path d="m4 10 4 4 8-9" />
            </svg>
            {t('authentic')}
          </span>

          <dl className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <div>
              <dt className="text-sm text-text-ter">{t('clubLabel')}</dt>
              <dd className="mt-1 font-medium text-text">{row.club_name}</dd>
            </div>
            <div>
              <dt className="text-sm text-text-ter">{t('periodLabel')}</dt>
              <dd className="mt-1 font-medium text-text">{periodLabel(row.period)}</dd>
            </div>
            <div className="sm:col-span-2">
              <dt className="text-sm text-text-ter">{t('issuedAtLabel')}</dt>
              <dd className="mt-1 font-medium text-text">
                {formatDateLong(new Date(row.issued_at))}
              </dd>
            </div>
          </dl>

          <p className="text-sm text-text-sec">{t('autoGenerated')}</p>
        </div>
      ) : (
        <div className="flex flex-col gap-4">
          <span
            className="inline-flex w-fit items-center gap-2 rounded-full bg-data-warning-50 px-3 py-1 text-sm font-semibold text-data-warning-strong"
            role="status"
          >
            <svg
              viewBox="0 0 20 20"
              className="h-4 w-4"
              aria-hidden="true"
              focusable="false"
              fill="none"
              stroke="currentColor"
              strokeWidth="2.5"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <path d="M10 6v5M10 14h.01" />
              <circle cx="10" cy="10" r="8" />
            </svg>
            {t('unknown')}
          </span>
          <p className="text-sm text-text-sec">{t('unknownHint')}</p>
        </div>
      )}
    </VerificationLayout>
  )
}
